### ISSUE TITLE
Have blank when view shared PDF

### ISSUE THREAD

**Issue by gg263** [owncloud/files_pdfviewer#85] opened 2015-12-07 14:26 UTC
https://drive.google.com/file/d/0B2dnmC72mCeWYU1DYUNiamFLbmM/view?usp=sharing
https://drive.google.com/file/d/0B2dnmC72mCeWWTVEbHgwVTRndUk/view?usp=sharing

Please check, when I visit the shared pdf, there is blank at the bottom.

I have this problem when using chrome Ver.46.0.2490.86 m and Firefox 42.0

Please see attached photo.

**Comment by LukasReschke** [comment] 2015-12-07 14:54
Duplicate of https://github.com/owncloud/core/issues/20557

**Closed by LukasReschke** 2015-12-07 14:54 UTC
